version: '3.8'

services:
 fluent-bit:
    image: fluent/fluent-bit:1.9.8
    container_name: coolify-fluentbit
    volumes:
      - ./logs:/logs
      - ./others/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./others/fluentbit/parser.conf:/fluent-bit/etc/parser.conf
    ports:
      - "24224:24224"
    networks:
      - coolify-infra
networks:
  coolify-infra:
    attachable: true
    name: coolify-infra
