version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      PUID: "${USERID:-9999}"
      PGID: "${GROUPID:-9999}"
      SSL_MODE: 'off'
    volumes:
      - .:/var/www/html
  postgres:
    image: postgres:15-alpine
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - db-coolify:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$DB_USERNAME",
          "-d",
          "db_prod"
        ]
      retries: 3
      timeout: 5s

volumes:
  db-coolify:
    driver: local
