version: "3.8"
services:
  coolify:
    image: "ghcr.io/coollabsio/coolify:${LATEST_IMAGE:-next}"
    container_name: coolify
    restart: always
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - coolify
    volumes:
      - type: bind
        source: /data/coolify/source/.env
        target: /var/www/html/.env
        read_only: true
      - /data/coolify/ssh:/var/www/html/storage/app/ssh
      - /data/coolify/applications:/var/www/html/storage/app/applications
      - /data/coolify/databases:/var/www/html/storage/app/databases
      - /data/coolify/backups:/var/www/html/storage/app/backups
    environment:
      - APP_ID
      - APP_ENV=production
      - APP_DEBUG
      - APP_NAME
      - APP_KEY
      - APP_URL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - QUEUE_CONNECTION
      - REDIS_HOST
      - REDIS_PASSWORD
      - SSL_MODE=off
      - PHP_PM_CONTROL=dynamic
      - PHP_PM_START_SERVERS=1
      - PHP_PM_MIN_SPARE_SERVERS=1
      - PHP_PM_MAX_SPARE_SERVERS=10
      - SELF_HOSTED
      - WAITLIST
      - SUBSCRIPTION_PROVIDER
      - STRIPE_API_KEY
      - STRIPE_WEBHOOK_SECRET
      - STRIPE_PRICE_ID_BASIC_MONTHLY
      - STRIPE_PRICE_ID_BASIC_YEARLY
      - STRIPE_PRICE_ID_PRO_MONTHLY
      - STRIPE_PRICE_ID_PRO_YEARLY
      - STRIPE_PRICE_ID_ULTIMATE_MONTHLY
      - STRIPE_PRICE_ID_ULTIMATE_YEARLY
      - PADDLE_VENDOR_ID
      - PADDLE_WEBHOOK_SECRET
      - PADDLE_VENDOR_AUTH_CODE
      - PADDLE_PUBLIC_KEY
      - PADDLE_PRICE_ID_BASIC_MONTHLY
      - PADDLE_PRICE_ID_BASIC_YEARLY
      - PADDLE_PRICE_ID_PRO_MONTHLY
      - PADDLE_PRICE_ID_PRO_YEARLY
      - PADDLE_PRICE_ID_ULTIMATE_MONTHLY
      - PADDLE_PRICE_ID_ULTIMATE_YEARLY
      - LEMON_SQUEEZY_API_KEY
      - LEMON_SQUEEZY_WEBHOOK_SECRET
      - LEMON_SQUEEZY_CHECKOUT_ID_BASIC_MONTHLY
      - LEMON_SQUEEZY_CHECKOUT_ID_BASIC_YEARLY
      - LEMON_SQUEEZY_CHECKOUT_ID_PRO_MONTHLY
      - LEMON_SQUEEZY_CHECKOUT_ID_PRO_YEARLY
      - LEMON_SQUEEZY_CHECKOUT_ID_ULTIMATE_MONTHLY
      - LEMON_SQUEEZY_CHECKOUT_ID_ULTIMATE_YEARLY
      - LEMON_SQUEEZY_BASIC_PLAN_IDS
      - LEMON_SQUEEZY_PRO_PLAN_IDS
      - LEMON_SQUEEZY_ULTIMATE_PLAN_IDS
    ports:
      - "<privateIP>:8000:80"
    healthcheck:
      test: curl --fail http://localhost:80/api/health || exit 1
      interval: 4s
      retries: 5
      timeout: 2s
networks:
    coolify:
        name: coolify
        driver: bridge
