version: '3.8'

services:
 fluent-bit:
    image: coollabsio/coolify-fluent-bit:1.0.0
    container_name: coolify-fluentbit
    volumes:
      - ./logs:/logs
    ports:
      - "24224:24224"
    networks:
      - coolify-infra
networks:
  coolify-infra:
    attachable: true
    name: coolify-infra
