blank_issues_enabled: true
contact_links:
  - name: 🤔 Questions and Help
    url: https://discord.com/invite/6rDM4fkymF
    about: Reach out to us on discord or our github discussions page.
  - name: 🙋‍♂️ service request
    url: https://feedback.coolify.io/
    about: want to request a new service? for e.g wordpress, hasura, appwrite etc...
