services:
  postgres:
    image: postgres
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - type: bind
        source: ./postgresql.conf
        target: /etc/postgresql/postgresql.conf
      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d/
        isDirectory: true
    environment:
      POSTGRES_USER: $SERVICE_USER_POSTGRES
      POSTGRES_PASSWORD: $SERVICE_PASSWORD_POSTGRES
