version: '3.5'

services:
  ${ID}:
    container_name: proxy-for-${PORT}
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:${PORT}
      - --providers.docker=false
      - --providers.docker.exposedbydefault=false
      - --providers.http.endpoint=http://host.docker.internal:3000/traefik.json?id=${ID}
      - --providers.http.pollTimeout=5s
      - --log.level=error
    ports:
      - '${PORT}:${PORT}'
    networks:
      - ${NETWORK}

networks:
  net:
    external: false
    name: ${NETWORK}
