version: '3'
services:
  newrelic-infra:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    networks:
      - coolify
    cap_add:
      - SYS_PTRACE
    privileged: true
    pid: host
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "newrelic-infra:/etc/newrelic-infra"
    environment:
      - NRIA_LICENSE_KEY=${NRIA_LICENSE_KEY}
      - NRIA_DISPLAY_NAME=${HOSTNAME}

networks:
  coolify:
