# This is an example dynamic configuration.
http:
  routers:
    devlab-http:
      entryPoints:
        - http
      service: devlab
      rule: Host(`devlab.id`)
  services:
    devlab:
      loadBalancer:
        servers:
          -
            url: 'http://devlab:80'