# documentation: https://www.activepieces.com/docs/getting-started/introduction
# slogan: Open source no-code business automation
# tags: workflow, automation, no code, open source
# logo: svgs/activepieces.png

version: '3.0'
services:
  activepieces:
    image: 'ghcr.io/activepieces/activepieces:0.21.0'
    container_name: activepieces
    restart: unless-stopped
    environment:
      - AP_API_KEY=$SERVICE_PASSWORD_64_APIKEY
      - AP_ENCRYPTION_KEY=$SERVICE_PASSWORD_64_ENCRYPTIONKEY
      - AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js
      - AP_ENVIRONMENT=prod
      - AP_EXECUTION_MODE=UNSANDBOXED
      - AP_FRONTEND_URL=$SERVICE_FQDN_ACTIVEPIECES
      - AP_JWT_SECRET=$SERVICE_PASSWORD_64_JWT
      - AP_POSTGRES_DATABASE=activepieces
      - AP_POSTGRES_HOST=postgres
      - AP_POSTGRES_PASSWORD=$SERVICE_PASSWORD_64_POSTGRES
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_USERNAME=$SERVICE_USER_POSTGRES
      - AP_REDIS_HOST=redis
      - AP_REDIS_PORT=6379
      - AP_SANDBOX_RUN_TIME_SECONDS=600
      - AP_TELEMETRY_ENABLED=true
      - 'AP_TEMPLATES_SOURCE_URL=https://cloud.activepieces.com/api/v1/flow-templates'
      - AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
      - AP_WEBHOOK_TIMEOUT_SECONDS=30
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_64_POSTGRES
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
