# documentation: https://www.classicpress.net/
# slogan: ClassicPress with external database. Classicpress A lightweight, stable, instantly familiar free open-source content management system. Based on WordPress without the block editor (Gutenberg).
# tags: cms, blog, content, management
# logo: svgs/classicpress.svg

services:
   wordpress:
     image: classicpress/classicpress:latest
     volumes:
       - classicpress-files:/var/www/html
     environment:
       - SERVICE_FQDN
       - CLASSICPRESS_DB_HOST=mysql
       - CLASSICPRESS_DB_USER=$SERVICE_USER_CLASSICPRESS
       - CLASSICPRESS_DB_PASSWORD=$SERVICE_PASSWORD_CLASSICPRESS
       - CLASSICPRESS_DB_NAME=classicpress
     depends_on:
       - mysql

   mariadb:
     image: mysql:5.7
     volumes:
       - mysql-data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
       - MYSQL_DATABASE=classicpress
       - MYSQL_USER=$SERVICE_USER_CLASSICPRESS
       - MYSQL_PASSWORD=$SERVICE_PASSWORD_CLASSICPRESS