# documentation: https://www.classicpress.net/
# slogan: ClassicPress with external database. Classicpress A lightweight, stable, instantly familiar free open-source content management system. Based on WordPress without the block editor (Gutenberg).
# tags: cms, blog, content, management
# logo: svgs/classicpress.svg

services:
   wordpress:
     image: classicpress/classicpress:latest
     volumes:
       - classicpress-files:/var/www/html
     environment:
       - SERVICE_FQDN
