# ignore: true
# documentation: https://docs.min.io/docs/minio-docker-quickstart-guide.html
# slogan: MinIO is a high performance object storage server compatible with Amazon S3 APIs.
# tags: object, storage, server, s3, api

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - SERVICE_FQDN_MINIO_9000
      - SERVICE_FQDN_CONSOLE_9001
      - MINIO_DOMAIN=$SERVICE_URL_MINIO_9000
      - MINIO_SERVER_URL=$SERVICE_FQDN_MINIO_9000
      - MINIO_BROWSER_REDIRECT_URL=$SERVICE_FQDN_CONSOLE_9001
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - minio-data:/data
