# documentation: https://github.com/coollabsio/next-image-transformation
# slogan: Self-hosted Next.js Image Transformation Service
# tags: nextjs,image,transformation,service

services:
  next-image-transformation:
    image: ghcr.io/coollabsio/next-image-transformation:latest
    environment:
      - SERVICE_FQDN_TRANSFORMATION
      - NODE_ENV=production
      - ALLOWED_REMOTE_DOMAINS=${ALLOWED_REMOTE_DOMAINS:-*}
      - IMGPROXY_URL=${IMGPROXY_URL:-http://imgproxy:8080}
    healthcheck:
      test: "wget -qO- http://localhost:3000/health || exit 1"
      interval: 2s
      timeout: 10s
      retries: 5
  imgproxy:
    image: darthsim/imgproxy
    environment:
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_USE_ETAG=true
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      interval: 2s
      timeout: 10s
      retries: 5
