# documentation: https://github.com/RobinLinus/snapdrop
# slogan: A self-hosted file-sharing service for secure and convenient file transfers, whether on a local network or the internet.
# tags: file, sharing, transfer, local, network, internet
# logo: svgs/unknown.svg

services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    environment:
      - SERVICE_FQDN_SNAPDROP
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - snapdrop-config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 2s
      timeout: 10s
      retries: 15
