# documentation: https://github.com/dani-garcia/vaultwarden
# slogan: Vaultwarden is a password manager that allows you to securely store and manage your passwords.
# tags: password manager, security
# logo: svgs/bitwarden.svg

services:
  vaultwarden:
    image: vaultwarden/server:latest
    environment:
      - SERVICE_FQDN_VAULTWARDEN
      - DOMAIN=${SERVICE_FQDN_VAULTWARDEN}
      - DATABASE_URL=${VAULTWARDEN_DB_URL:-data/db.sqlite3}
      - SIGNUPS_ALLOWED=${SIGNUP_ALLOWED:-true}
      - ADMIN_TOKEN=${SERVICE_PASSWORD_64_ADMIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Vaultwarden}
      - SMTP_USERNAME=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASS}
      - SMTP_SECURITY=${SMTP_SECURITY:-starttls}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_TIMEOUT=15
      - PUSH_ENABLED=${PUSH_ENABLED:-false}
      - PUSH_INSTALLATION_ID=${PUSH_SERVICE_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_SERVICE_KEY}
    volumes:
      - vaultwarden-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15
