# documentation: https://wordpress.org/documentation/
# slogan: WordPress with external database. Wordpress is open source software you can use to create a beautiful website, blog, or app.
# tags: cms, blog, content, management

services:
   wordpress:
     image: wordpress:latest
     volumes:
       - wordpress-files:/var/www/html
     environment:
       SERVICE_FQDN:
       WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
       WORDPRESS_DB_USER: $WORDPRESS_DB_USER
       WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
       WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
