version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: coolify-redis
    networks:
      - coolify-infra
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
  # fluentbit:
  #     container_name: coolify-fluentbit
  #     build:
  #       context: ./data/fluentd
  #       dockerfile: Dockerfile-dev
  #     ports:
  #       - target: 24224
  #         published: 24224
  #         protocol: tcp
  #         mode: host
  #       - target: 24224
  #         published: 24224
  #         protocol: udp
  #         mode: host
  #     networks:
  #       - coolify-infra
  #     extra_hosts:
  #       - 'host.docker.internal:host-gateway'
networks:
  coolify-infra:
    attachable: true
    name: coolify-infra
