name: release-coolify

on:
  push:
    branches:
      - 'gh-actions'

jobs:
  make-it-coolifyed:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       - 
        name: Read package.json version
        uses: dutscher/read-package-json-endpoint-actions@v1.3.37
        id: packagejson
       -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: coollabsio/coolify-test:latest,coollabsio/coolify-test:${{ steps.packagejson.version }}
          cache-from: type=registry,ref=coollabsio/coolify-test:buildcache
          cache-to: type=registry,ref=coollabsio/coolify-test:buildcache,mode=max
