name: ci

on:
  push:
    branches:
      - 'gh-actions'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       - 
        name: Cache pnpm modules
        uses: actions/cache@v2
        with:
           path: ~/.pnpm-store
           key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
           restore-keys: |
             ${{ runner.os }}-

       - 
         uses: pnpm/action-setup@v2.1.0
         with:
            version: 7.0.0
            run_install: false
       -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: coollabsio/coolify-test:latest
