name: release-coolify

on:
  push:
    branches:    
      - main

jobs:
  make-it-coolifyed:
    runs-on: ubuntu-latest
    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
       -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
       -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       - 
         name: Get current package version
         uses: martinbeentjes/npm-get-version-action@v1.2.3
         id: package-version
       -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: coollabsio/coolify:latest,coollabsio/coolify:${{steps.package-version.outputs.current-version}}
          cache-from: type=registry,ref=coollabsio/coolify:buildcache
          cache-to: type=registry,ref=coollabsio/coolify:buildcache,mode=max
