name: staging-release

on:
  push:
    paths:
      - "**"
      - "!others/fluentbit"
      - "!others/pocketbase"
      - "!.github/workflows/fluent-bit-release.yml"
      - "!.github/workflows/pocketbase-release.yml"
    branches:
      - next

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "next"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.2.3
        id: package-version
      - name: Docker meta
        id: staging
        uses: docker/metadata-action@v3
        with:
          images: coollabsio/coolify
          tags: |
            type=ref,event=branch
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ${{ steps.staging.outputs.tags }}
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_DEV_RELEASE_CHANNEL }}
